### ISSUE TITLE
Added Okta

### ISSUE THREAD

**Issue by Havokmon** [david-ramsden/paloalto-edl#2]
Sorry - new to github.
[edl.php.patch.txt](https://github.com/david-ramsden/paloalto-edl/files/9193154/edl.php.patch.txt)

**Comment by Havokmon** [comment]
1 - Swapped variables in preg_match    now 'service=us_cell' will match all instances of us_cell for vendor okta
2 - adjusted error_log in display_ips() to log service
[edl.php.patch.2.txt](https://github.com/david-ramsden/paloalto-edl/files/9195420/edl.php.patch.2.txt)

**Comment by david-ramsden** [comment]
Hey @Havokmon! Sorry it has taken me so long to review this. It's the holidays, so I'll get around to reviewing your PR #3
